version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./silverkingbrazil:/var/www/html
    ports:
      - "8001:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
